baseURL = 'https://www.zhatrix.com/'
DefaultContentLanguage = "zh"
languageCode = 'zh-cn'
title = 'ZhaTrix的闲言碎语、工具箱和游乐场'
theme = 'beautifulhugo'
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
hasCJKLanguage = true  #开启后中文统计才正常，否则影响文章的概览字数统计，以及首页列表显示内容
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    # id = "XXX"

# [languages]
#   [languages.zh]
#     contentDir = "content/zh" # Chinese
#   [languages.en]
#     contentDir = "content/en" # English

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[Params]
  # homeTitle = "ZhaTrix 的闲言碎语、工具箱和游乐场" # Set a different text for the header on the home page
  subtitle = "不希望对你有用，只希望让未来的我知道曾经经历过"
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  # dateFormat = "January 2, 2006"
  dateFormat = "2006-01-02"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  # socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  showPageDates = true
  summaryLength = 150  # 启用 hasCJKLanguage 后按中文字符计数，约10行概览
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"


[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "ZhaTrix"
  website = "zhatrix.com"
  github = "zhatrix"
  twitter = "zhangzhenyu"
  weibo = "armszhang"

[[menu.main]]
    name = "文章"
    url = ""
    weight = 1

[[menu.main]]
    name = "标签"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "归档"
    url = "page/archive/"
    weight = 2

[[menu.main]]
    name = "关于我"
    url = "page/about/"
    weight = 4

[[menu.main]]
    identifier = "products"
    name = "我的项目"
    weight = 5

[[menu.main]]
    parent = "products"
    name = "趣玩"
    url = "page/fungo/"
    weight = 1

[[menu.main]]
    parent = "products"
    name = "奶爸工具箱"
    url = "page/parentool/"
    weight = 2

# [[menu.main]]
#     parent = "samples"
#     name = "Code Sample"
#     url = "post/2016-03-08-code-sample"
#     weight = 3
